# Generated by Django 5.0.4 on 2024-05-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='vieos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=70)),
                ('total_items', models.IntegerField()),
                ('before_tittle', models.CharField(max_length=70)),
                ('id_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guias')),
            ],
        ),
    ]
