# Generated by Django 5.0.4 on 2024-05-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('acronimo', models.CharField(default='', max_length=10)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default='', max_length=70)),
                ('img_name', models.CharField(default='', max_length=70)),
                ('old_name', models.CharField(default='', max_length=70)),
                ('extension', models.CharField(default='', max_length=10)),
                ('code', models.CharField(default='', max_length=10)),
                ('script', models.TextField(null=True)),
                ('acronimo', models.CharField(default='', max_length=10)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
