# Generated by Django 4.2.13 on 2024-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='img_name',
            new_name='video_img_name',
        ),
        migrations.AddField(
            model_name='video',
            name='extra_img_name1',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='extra_img_name2',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='num_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='acronimo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='extension',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='old_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(max_length=70),
        ),
    ]
