# Generated by Django 5.0.4 on 2024-05-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guias',
            new_name='guia',
        ),
        migrations.RenameModel(
            old_name='vieos',
            new_name='video',
        ),
    ]
