# Generated by Django 4.2.13 on 2024-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_img_name_video_video_img_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='script',
            field=models.TextField(),
        ),
    ]
