# Generated by Django 5.0.4 on 2024-05-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_video_before_tittle_remove_video_tittle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='num_items',
            new_name='num_item',
        ),
        migrations.AddField(
            model_name='video',
            name='old_title',
            field=models.CharField(default='', max_length=70),
        ),
    ]
