# Generated by Django 4.2.13 on 2024-05-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_video_extra_img_name1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_name',
            field=models.TextField(),
        ),
    ]
