# Generated by Django 4.2.13 on 2024-06-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_video_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fecha',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='position',
            field=models.TextField(default=''),
        ),
    ]
