# Generated by Django 4.2.13 on 2024-06-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_video_fecha_video_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
    ]
